[package]
name = "autonomi_dash"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
regex = "1"
glob = "0.3"
ratatui = "0.26"
crossterm = "0.27"
anyhow = "1.0"
dirs = "5.0"
futures = "0.3.31"
